name: Run tests
run-name: Test website work
on: [push]
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - run: cd code

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - run: npm run dev
      - run: npm run test